apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tjum7h7o1-dotnet-basic
  janus-idp.io/tekton: tjum7h7o1-dotnet-basic
  backstage.io/kubernetes-id: tjum7h7o1-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tjum7h7o1-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
