apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tjum7h7o1-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:2e13580f41ef83f71e0b6aa1c88d2599b09c94bf@sha256:9d2f11449dc9d68fe5f89741863b272389b881fe698bacb790a8c3cc00b6f1fa
          name: container-image
